from classes import *
#
# a = Matrix([[2, 5, 7], [6, 3, 4], [5, -2, -3]])
# b = Matrix([[4, -2, 1], [1, 6, -2], [1, 0, 0]])
# print("Mатрица А:")
# for i in range(0, 3):
#     print(*a[i])
# print("")
# print("Матрица В:")
# for i in range(0, 3):
#     print(*b[i])
# print("")
# print("A * B =")
# print(*(a * b)[0])
# print(*(a * b)[1])
# print(*(a * b)[2])
# print("")
# print("B * A =")
# print(*(b * a)[0])
# print(*(b * a)[1])
# print(*(b * a)[2])
# print("")
# print("B + A =")
# print(*(b + a)[0])
# print(*(b + a)[1])
# print(*(b + a)[2])
# print("")
# print("A + B =")
# print(*(a + b)[0])
# print(*(a + b)[1])
# print(*(a + b)[2])
# print("")
# print("B - A =")
# print(*(b - a)[0])
# print(*(b - a)[1])
# print(*(b - a)[2])
# print("")
# print("A - B =")
# print(*(a - b)[0])
# print(*(a - b)[1])
# print(*(a - b)[2])
# print("")
# print("A * 5 =")
# print(*(a * 5)[0])
# print(*(a * 5)[1])
# print(*(a * 5)[2])
# print("")
# print("5 * A =")
# print(*(5 * a)[0])
# print(*(5 * a)[1])
# print(*(5 * a)[2])
# print("")
# for i in range(0, 3):
#     print(*a[i])
# print("Транспонированная матрица А:")
# print(*(a.transpose())[0])
# print(*(a.transpose())[1])
# print(*(a.transpose())[2])
# print("")
# print("Транспонированная матрица B:")
# print(*(b.transpose())[0])
# print(*(b.transpose())[1])
# print(*(b.transpose())[2])
# print("")
# print("Матрица, обратная А:")
# print(*(a.inverse())[0])
# print(*(a.inverse())[1])
# print(*(a.inverse())[2])
# print("")
# print("Матрица, обратная B:")
# print(*(b.inverse())[0])
# print(*(b.inverse())[1])
# print(*(b.inverse())[2])
# print("")
# print("Определитель А:")
# print(a.determinant())
# print("")
# print("Определитель B:")
# print(b.determinant())
# print("")
# c = Matrix([[1, 2], [6, 2]])
# print("Матрица С:")
# print(*c[0])
# print(*c[1])
# print("")
# print("Определитель C:")
# print(c.determinant())
# print("")
# d = Matrix([[3, 2, 6, 1], [6, 2, 9, 0], [3, 10, 2, 8], [1, 3, 0, 6]])
# print("Матрица D:")
# print(*d[0])
# print(*d[1])
# print(*d[2])
# print(*d[3])
# print("")
# print("Определитель D:")
# print(d.determinant())
# print("Матрица, обратная D:")
# print(*(d.inverse())[0])
# print(*(d.inverse())[1])
# print(*(d.inverse())[2])
# print(*(d.inverse())[3])
# print("")
# e = Matrix([[2]])
# print("Матрица E:")
# print(*e[0])
# print("Определитель E:")
# print(e.determinant())
# a = Matrix([[2, 5, 7], [6, 3, 4], [5, -2, -3], [1, 0, 8]])
# b = Matrix([[4, -2, 1, 4, 0], [1, 6, -2, 2, -6], [1, 0, 0, 7, -3]])
# print("Mатрица А:")
# for i in range(0, 4):
#     print(*a[i])
# print("")
# print("Матрица В:")
# for i in range(0, 3):
#     print(*b[i])
# print("")
# print("A * B =")
# print(*(a * b)[0])
# print(*(a * b)[1])
# print(*(a * b)[2])
# print(*(a * b)[3])
# print("")
# print("Транспонированная матрица А:")
# print(*(a.transpose())[0])
# print(*(a.transpose())[1])
# print(*(a.transpose())[2])
# print("")
# print("Транспонированная матрица B:")
# print(*(b.transpose())[0])
# print(*(b.transpose())[1])
# print(*(b.transpose())[2])
# print(*(b.transpose())[3])
# print(*(b.transpose())[4])
# print("")
#
# a = Vector([1, 3, 5, 2, 0])
# b = Vector([4, 0, 1, 8, 3])
# print("Вектор А:")
# print(*a.matrix)
# print("")
# print("Вектор В:")
# print(*b.matrix)
# print("")
# print("Скалярное произведение A * B:")
# print(a % b)
# print("")
# print("Скалярное произведение B * A:")
# print(b % a)
# print("")
# print("Длина А:")
# print(a.length())
# print("")
# print("Длина B:")
# print(b.length())
# print("")
# a = Vector([1, 3, 5])
# b = Vector([4, 0, 1])
# print("Вектор А:")
# print(*a.matrix)
# print("")
# print("Вектор В:")
# print(*b.matrix)
# print("")
# print("Скалярное произведение A * B:")
# print(a % b)
# print("")
# print("Скалярное произведение B * A:")
# print(b % a)
# print("")
# print("Длина А:")
# print(a.length())
# print("")
# print("Длина B:")
# print(b.length())
# print("")
#
# p = Point([1, 0, 4])
# print("Координаты точки Р:")
# print(*p.coordinates)
# print("")
# print("P + A:")
# print((p + a).coordinates)
# print("")
# print("P + B:")
# print((p + b).coordinates)
# print("")
# print((a + p).coordinates)
# print("")
#
# a = Matrix([[2, 5, 7], [6, 3, 4], [5, -2, -3], [1, 2, 3]])
# print(len(a.matrix))
#
# a = Matrix.identity(5)
# print(a.matrix)



v1 = Vector([[1, 2, 3]])
v2 = Vector([[3, 7, 8]])
print((v1 ** v2).matrix)
